version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      -  '27017:27017'   #port 27017 is exposed on the host
    volumes:
      - mongo_data:/data/db
       
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings:DatabaseName=Catalog"
      - "DatabaseSettings:CollectionName=Products"
    depends_on:
      - catalogdb    
    ports:
      - "8000:80"
