version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      -  '27017:27017'   #port 27017 is exposed on the host
    volumes:
      - mongo_data:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      -  '6379:6379'   #port 6379 is exposed on the host

  discountdb:
    container_name: discountdb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: DiscountDb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  orderdb:
    container_name: orderdb
    restart: always
    environment:
      SA_PASSWORD: "test123#"
      ACCEPT_EULA: "Y"
    ports:
      - 1434:1433
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      -  '5672:5672'   #port 5672 is exposed on the host
      - '15672:15672'   #port 15672 is exposed on the host

  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      -  '8080:8000'   
      -  '9000:9000'   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - portainer_data:/data
  
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings:DatabaseName=Catalog"
      - "DatabaseSettings:CollectionName=Products"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "EventBusSettings:Host=amqp://rabbitmq:5672"
      - "EventBusSettings:Username=guest"
      - "EventBusSettings:Password=guest"

    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:80"  
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin123;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"  
  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin123;"
    depends_on:
      - discountdb
    ports:
      - "8003:80"  
  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=test123#"  
      - "EventBusSettings:Host=amqp://rabbitmq:5672"
      - "EventBusSettings:Username=guest"
      - "EventBusSettings:Password=guest"
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8004:80"
  
  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - order.api
    ports:
      - "8010:80"  
    